staging: fsl_qbman: include new header file linux/dma-mapping.h
commit  cfad64e9999d84ebab3bee805b4035f35088f904 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

New headfile introduced from:
0a0f0d8be76d ("dma-mapping: split <linux/dma-mapping.h>")

Including it to fix the build issue below:

drivers/staging/fsl_qbman/qman_high.c: In function ‘qman_create_portal’:
drivers/staging/fsl_qbman/qman_high.c:687:2: error: implicit declaration of function ‘arch_setup_dma_ops’; did you mean ‘arch_setup_new_exec’? [-Werror=implicit-function-declaration]
  arch_setup_dma_ops(&portal->pdev->dev, 0, 0, NULL, true);
  ^~~~~~~~~~~~~~~~~~
  arch_setup_new_exec

Signed-off-by: Li Yang <leoyang.li@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>