smb: client: fix smb2ops.c compile error
When enabled allyesconfig in yocto, the error happens:

    fs/cifs/smb2ops.c:320:33: error: too few arguments to function 'server->ops->calc_smb_size'
    |   320 |                                 server->ops->calc_smb_size(buf));
    |       |                                 ^~~~~~

Fixes: 70a41e4b4d83 ("smb: client: fix potential OOB in smb2_dump_detail()")
Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>