dmaengine: xilinx: mmi_dcdma: Add missing bitfield.h include
commit f538cc78663e177a5be9594ee4617223e8e398b7 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.18

Add the missing linux/bitfield.h header which provides the FIELD_GET()
macro used in mmi_dcdma_chan_done() function.

Without this include, the build fails with:

  drivers/dma/xilinx/mmi_dcdma.c: In function 'mmi_dcdma_chan_done':
  drivers/dma/xilinx/mmi_dcdma.c:713:21: error: implicit declaration of
  function 'FIELD_GET' [-Werror=implicit-function-declaration]

Fixes: 68c97a99c042 ("dmaengine: xilinx: Add MMI DCDMA driver")
Reported-by: Bhanu Teja Yadav Perugu <byadavpe@amd.com>
Reviewed-by: Vishal Sagar <vishal.sagar@amd.com>
Signed-off-by: Michal Simek <michal.simek@amd.com>
Message-ID: <b7d1a8573bdd71cc2229e5a943a553c4891fc60c.1775573567.git.michal.simek@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>