fs/yaffs2: fix a build warning in yaffs_mtdif.c when running make allyesconfig
When building linux yocto with allyesconfig, a build warning is
found:

fs/yaffs2/yaffs_mtdif.c:48:5: error: no previous prototype for
‘nandmtd_erase_block’ [-Werror=missing-prototypes]
   48 | int nandmtd_erase_block(struct yaffs_dev *dev, int block_no)
      |     ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Inspect the code that the function nandmtd_erase_block() is
not used by yaffs2. So remove it.

Signed-off-by: Bin Lan <bin.lan.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>