linux/irqchip.h: add extra fields for IRQCHIP_PLATFORM_DRIVER_END
When building linux yocto with allyesconfig on zynqmp bsp in devshell,
a build error is found:

amd-zynqmp/kernel-source/drivers/irqchip/irq-imx-mu-msi.c:448:61: error:
macro "IRQCHIP_PLATFORM_DRIVER_END" passed 2 arguments, but takes just 1
  448 | IRQCHIP_PLATFORM_DRIVER_END(imx_mu_msi, .pm = &imx_mu_pm_ops)
      |                                                             ^
In file included from
amd-zynqmp/kernel-source/drivers/irqchip/irq-imx-mu-msi.c:15:
amd-zynqmp/kernel-source/include/linux/irqchip.h:68:
note: macro "IRQCHIP_PLATFORM_DRIVER_END" defined here
   68 | #define IRQCHIP_PLATFORM_DRIVER_END(drv_name)
      \
      |
  CC      drivers/regulator/irq_helpers.o
  CC      drivers/block/pktcdvd.o
  CC      drivers/iommu/arm/arm-smmu/arm-smmu-nvidia.o
amd-zynqmp/kernel-source/drivers/irqchip/irq-imx-mu-msi.c:448:1:
error: 'IRQCHIP_PLATFORM_DRIVER_END' undeclared here (not in a function)
  448 | IRQCHIP_PLATFORM_DRIVER_END(imx_mu_msi, .pm = &imx_mu_pm_ops)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Allow extra fields to be passed to IRQCHIP_PLATFORM_DRIVER_END since
334f7d42db3e ("irqchip: Allow extra fields to be passed to
IRQCHIP_PLATFORM_DRIVER_END"). IRQCHIP_PLATFORM_DRIVER_END is defined
twice through the compilation macro. One of them has not been changed
accordingly. Update it.

Signed-off-by: Bin Lan <bin.lan.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>