gpu: mali: do not check return for dma_set_max_seg_size
commit  d0685a3648c7d19d7e2205a8c1f7475a767c61e1 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Cope with upstream API change:
commit 334304ac2bac ("dma-mapping: don't return errors from dma_set_max_seg_size")

  CC      drivers/gpu/arm/midgard/device/mali_kbase_device.o
../drivers/gpu/arm/midgard/device/mali_kbase_device.c: In function ‘kbase_device_misc_init’:
../drivers/gpu/arm/midgard/device/mali_kbase_device.c:311:21: error: void value not ignored as it ought to be
  311 |                 err = dma_set_max_seg_size(kbdev->dev, UINT_MAX);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>