drm: xlnx: pl_disp: use fourcc_code instead of strscpy
Write 5 bytes to a int type variable will trigger the following error
when enabling FORTIFY_SOURCE:

    In function ‘sized_strscpy’,
	inlined from ‘xlnx_pl_disp_probe’ at drivers/gpu/drm/xlnx/xlnx_pl_disp.c:615:2:
    include/linux/fortify-string.h:293:17: error: call to ‘__write_overflow’ declared with attribute error: detected write beyond size of object (1st parameter)
    293 |                 __write_overflow();
	|                 ^~~~~~~~~~~~~~~~~~

Use the fourcc_code function to get a DRM_FORMAT_XXX value from string
instead of strscpy.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>