LF-6810-03: media: Samsung CSI2: fix build error due to API renamed
commit  cef963a6d72b8e5f578c4286ee08cc9b9815387f from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Fix Samsung MIPI CSI2 driver build error due to API renamed in bellow commit:
drivers/staging/media/imx/imx8-mipi-csi2-sam.c:594:46:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>