net: stmmac: Remove some code unintentionally introduced by the merge commit
These changes were introduced by merge commit dc65a6ec37ba ("Merge
branch 'v5.15/standard/base' into v5.15/standard/bcm-2xxx-rpi"), they
didn't exist in the original branch or the stable kernel. Remove them
to fix the following build errors:
drivers/net/ethernet/stmicro/stmmac/dwmac4_core.c:1228:10: error: ‘const struct stmmac_ops’ has no member named ‘fpe_configure_get’; did you mean ‘fpe_configure’?
 1228 |         .fpe_configure_get = dwmac5_fpe_configure_get,
      |          ^~~~~~~~~~~~~~~~~
      |          fpe_configure
drivers/net/ethernet/stmicro/stmmac/dwmac4_core.c:1228:30: error: ‘dwmac5_fpe_configure_get’ undeclared here (not in a function); did you mean ‘dwmac5_fpe_configure’?
 1228 |         .fpe_configure_get = dwmac5_fpe_configure_get,
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~
      |                              dwmac5_fpe_configure
drivers/net/ethernet/stmicro/stmmac/dwmac4_core.c:1281:10: error: ‘const struct stmmac_ops’ has no member named ‘fpe_configure_get’; did you mean ‘fpe_configure’?
 1281 |         .fpe_configure_get = dwmac5_fpe_configure_get,
      |          ^~~~~~~~~~~~~~~~~
      |          fpe_configure

Signed-off-by: Kevin Hao <haokexin@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>