MGS-8076 gpu: imx: dpu-blit: fix the using of MODULE_IMPORT_NS in 6.13 kernel
commit  1826318e785461db2a0c718dd8957ca11e2df5e2 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Fix the using of MODULE_IMPORT_NS in 6.13 kernel.

drivers/gpu/drm/imx/dpu/dpu-blit.c:393:18: error: expected ‘,’ or ‘;’ before ‘DMA_BUF’
  393 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
API usage changed since
commit ocdd30ebb1b9f ("module: Convert symbol namespace to string literal")

Signed-off-by: Guangliu Ding <guangliu.ding@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>