hotfix: net: fec_uio: fix build issue
commit  8b2d51445c225adfe30b2e63a20e3a60cc998b79 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

API changed since the commit 83f55b01dd90 ("net: stmmac: rename xpcs_an_inband to default_an_inband")

../drivers/net/ethernet/freescale/fec_uio.c: In function ‘stmmac_phy_setup’:
../drivers/net/ethernet/freescale/fec_uio.c:425:38: error: ‘struct stmmac_mdio_bus_data’ has no member named ‘xpcs_an_inband’
  425 |                         mdio_bus_data->xpcs_an_inband;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>