crypto: tls - Use data directly in completion function
commit  81f4f314b644e671e23a796029d28c6e4abb05f5 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Facing build error in building tls
error: passing argument 3 of ?ahash_request_set_callback?
from incompatible pointer type [-Werror=incompatible-pointer-types]

Issue introduced after changing prototype of "crypto_completion_t"
function pointer in include/linux/crypto.h, conversion of
completion function of tls was missed.

Changes are done to use data directly in completion function of tls.

Fixes: 255e48eb1768 ("crypto: api - Use data directly in completion function")
Signed-off-by: Meenakshi Aggarwal <meenakshi.aggarwal@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>