dwc3/host.c: remove unused variable
drivers/usb/dwc3/host.c:30:21: error: variable 'dwc3_xhci_plat_priv' has initializer but incomplete type
   30 | static const struct xhci_plat_priv dwc3_xhci_plat_priv = {
      |                     ^~~~~~~~~~~~~~
drivers/usb/dwc3/host.c:31:10: error: 'const struct xhci_plat_priv' has no member named 'quirks'                                                                                               31 |         .quirks = XHCI_SKIP_PHY_INIT,
      |          ^~~~~~

Signed-off-by: Li Wang <li.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>