mxc: gpu-viv: remove set but unused 'writePtrReg' in _ProgramDescRingBuf()
commit  d09b7c4f85681ec5584fa954d8259d49a3e71537 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Since commit 1688134b59d6 ("Update to 6.4.11 gpu driver version."), the
"Priority ring buffer write ptr." function call was removed, leaving
behind an unused writePtrReg which causes this:

drivers/mxc/gpu-viv/hal/kernel/arch/gc_hal_kernel_hardware_mc_fe.c:255:15: error:
variable 'writePtrReg' set but not used [-Werror,-Wunused-but-set-variable]
    gctUINT32 writePtrReg;
              ^
1 error generated.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>