LF-16506-4 net: fec_uio: Update first parameter of fix_soc_reset
commit  16d681f10795c53bb786ee712ec88ff185035476 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Cope with upstream change:
commit 139235103f60 ("net: stmmac: Change first parameter of fix_soc_reset()")

drivers/net/ethernet/freescale/fec_uio.c: In function ‘enet_qos_probe’:
drivers/net/ethernet/freescale/fec_uio.c:736:40: error: assignment to ‘int (*)(struct stmmac_priv *, void *)’ from incompatible pointer type ‘int (*)(void *, void *)’ [-Werror=incompatible-pointer-types]
  736 |         dwmac->plat_dat->fix_soc_reset = dwmac->ops->fix_soc_reset;
      |

Reviewed-by: Vanshika Shukla <vanshika.shukla@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>