mxc: gpu-viv: delete set but unused 'j' in set_clk()
commit  ed454991b3da995d2b7c8a4a0daeebaf5b78825c from
https://github.com/nxp-imx/linux-imx lf-6.18.y

In a clang-16 build with W=1 C=1, this warning is treated as an error:

drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_device.c:1132:21: error:
variable 'j' set but not used [-Werror,-Wunused-but-set-variable]
    gctINT       n, j, k;
                    ^

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>