drivers: soc: marvell: fix unused variable warning in otx2-pci-console.c
Fixed following compilation warnings.
  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:
    In function 'pci_console_nexus_de_init_resources'
  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:233:24:
    error: unused variable 'dev' [-Werror=unused-variable]

  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:
    In function 'pci_console_nexus_shutdown':
  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:397:24:
    error: unused variable 'dev' [-Werror=unused-variable]

  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:
    In function 'pci_console_dev_device':
  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:843:24:
    error: unused variable 'dev' [-Werror=unused-variable]

  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:
    In function 'pci_console_shutdown':
  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:1167:24:
    error: unused variable 'dev' [-Werror=unused-variable]

  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:
    In function 'pci_console_dev_tty_open':
  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:1278:24:
    error: unused variable 'dev' [-Werror=unused-variable]

  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:
    In function 'pci_console_dev_tty_close':
  drivers/soc/marvell/octeontx2-pcicons/otx2-pci-console.c:1298:24:
    error: unused variable 'dev' [-Werror=unused-variable]

Fixes: 4e2d27a73104 ("drivers: soc: marvell: Add PCI console driver")
Signed-off-by: Rui He <rui.he@windriver.com>