brcmfmac: Fix implicit declaration build error
The following build error was triggered because of header file not included

fwil.h: error: implicit declaration of function 'brcmf_dbg'

This happens from the commit c3cfcf51b4e01 ("wifi: brcmfmac: export firmware
interface functions"). Included the header file debug.h to fix it.

Signed-off-by: Rajeshkumar Ramasamy <rajeshkumar.ramasamy@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>