fs/aufs: fix a build warning in sysrq.c when running make allyesconfig
When building linux yocto with allyesconfig, a build warning is found:

s/aufs/sysrq.c:120:27: error: initialization of ‘void (*)(u8)’ {aka
‘void (*)(unsigned char)’} from incompatible pointer type ‘void
(*)(int)’ [-Werror=incompatible-pointer-types]
  120 |         .handler        = au_sysrq,
      |                           ^~~~~~~~
fs/aufs/sysrq.c:120:27: note: (near initialization for
‘au_sysrq_op.handler’)
cc1: all warnings being treated as errors

The first parameter, key, in the function au_sysrq() is unused.
Therefore, change its type to u8.

Signed-off-by: Bin Lan <bin.lan.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>