octeontx2-af: fix cflags include paths
commit 78e5f58778fc9b66f89c47a10efcd3d6bc269735 from
git@git.assembla.com:cavium/WindRiver.linux.git

When build out of tree with external toolchain
cflags include path is broken as well as EB_DIR.

Fixes:
cflags using srctree:
drivers/net/ethernet/marvell/octeontx2/af/rvu.c:24:10: fatal error:
rvu_eblock.h: No such file or directory
..

EB_DIR refernce path:
make[7]: *** No rule to make target
'drivers/net/ethernet/marvell/octeontx2/af/
../../../../../../drivers/soc/marvell/rvu_af_extn//rvu_eblock.o', needed by
'drivers/net/ethernet/marvell/octeontx2/af/rvu_af.o'.  Stop
..

Fixes: 3b533a786640 ("octeontx2-af: Add RVU AF extension block interface")

Change-Id: Ifec7bbbf2eb7ef68f9313a0b1ed5e9682c1eba0e
Signed-off-by: Wladislav Wiebe <wladislav.wiebe@nokia.com>
Signed-off-by: Linu Cherian <lcherian@marvell.com>
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/119082
Tested-by: sa_ip-sw-jenkins <sa_ip-sw-jenkins@marvell.com>
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Signed-off-by: Bo Sun <Bo.Sun.CN@windriver.com>