LF-10718 drm/bridge: imx95-mipi-dsi: Fix build error with Clang
commit  1c2f330dbdf334ae292a6eed2186b1195268773f from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Macro PHY_TESTDIN(n) is defined as "FIELD_PREP(GENMASK(7, 0), (n))".

The mask for FIELD_PREP() is 8-bit wide.  Some constant values are handed
over to PHY_TESTDIN() as parameters in the driver and overflow the field
represented by the mask.  Mask those constant values with 0xff to fix the
issue.  This fix only makes compiler happy.  No functional change.

../drivers/gpu/drm/bridge/imx/imx95-mipi-dsi.c:471:55: error: call to '__compiletime_assert_483' declared with 'error' attribute: FIELD_PREP: value too large for the field
        imx95_dsi_write(dsi, DSI_PHY_TST_CTRL1, PHY_TESTEN | PHY_TESTDIN(test_code));
                                                             ^
../drivers/gpu/drm/bridge/imx/imx95-mipi-dsi.c:45:27: note: expanded from macro 'PHY_TESTDIN'
                                        ^
../include/linux/bitfield.h:114:3: note: expanded from macro 'FIELD_PREP'
                __BF_FIELD_CHECK(_mask, 0ULL, _val, "FIELD_PREP: ");    \
                ^
../include/linux/bitfield.h:68:3: note: expanded from macro '__BF_FIELD_CHECK'
                BUILD_BUG_ON_MSG(__builtin_constant_p(_val) ?           \
                ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
./../include/linux/compiler_types.h:413:2: note: expanded from macro '_compiletime_assert'
        __compiletime_assert(condition, msg, prefix, suffix)
        ^
./../include/linux/compiler_types.h:406:4: note: expanded from macro '__compiletime_assert'
                        prefix ## suffix();                             \
                        ^
<scratch space>:40:1: note: expanded from here
__compiletime_assert_483
^
1 error generated.

Reported-by: Jindong Yue <jindong.yue@nxp.com>
Signed-off-by: Liu Ying <victor.liu@nxp.com>
Reviewed-by: Sandor Yu <Sandor.yu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>