drm/amdgpu/jpeg: Fix sprintf buffer overflow warning in jpeg_v2_5
commit c2f750ebdd983fa07d651de3fcfbf9ebaff078cc from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.18

Replace sprintf() with snprintf() to fix the -Werror=format-overflow
warning when building with allmodconfig:

  drivers/gpu/drm/amd/amdgpu/jpeg_v2_5.c:152:47: error: '%d' directive
  writing between 1 and 11 bytes into a region of size 7
  [-Werror=format-overflow=]
    152 |                 sprintf(ring->name, "jpeg_dec_%d", i);

The ring->name buffer is 16 bytes. Using snprintf() with sizeof()
ensures the buffer cannot overflow regardless of the integer value.

Reviewed-by: Christian König <christian.koenig@amd.com>
Link: https://patch.msgid.link/1be91839e8b3e41003147a8cdc99e6efd1a87442.1776146550.git.michal.simek@amd.com
Signed-off-by: Michal Simek <michal.simek@amd.com>
Message-ID: <b123156258a5098b76e464aeac7229d41f0f123e.1776174491.git.michal.simek@amd.com>
State: waiting
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>