mxc: gpu-viv: remove set but unused 'timeline' in gckOS_WaitNativeFence()
commit  873ec9185758359fc4f239270175cb383f9da0ae from
https://github.com/nxp-imx/linux-imx lf-6.18.y

../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:6803:31: error:
variable 'timeline' set but not used [-Werror,-Wunused-but-set-variable]
    struct viv_sync_timeline *timeline;
                              ^
1 error generated.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>