misc: mrvl-loki: Add missing forward declarations
commit 0ad2a8fc9ee8d35b5566371ad59ff99bc866361b from
git@git.assembla.com:cavium/WindRiver.linux.git

  | drivers/misc/mrvl-loki.c:48:5: error: no previous prototype for 'mrvl_loki_register_irq_cb' [-Werror=missing-prototypes]
  |    48 | int mrvl_loki_register_irq_cb(connip_irq_cb_t func)
  |       |     ^~~~~~~~~~~~~~~~~~~~~~~~~
  | drivers/misc/mrvl-loki.c:64:6: error: no previous prototype for 'mrvl_loki_unregister_irq_cb' [-Werror=missing-prototypes]
  |    64 | void mrvl_loki_unregister_irq_cb(void)
  |       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~

%JID=FCA_PS_LFS-165283
%TBC %NF=CB014946-SR-B-B1

Change-Id: Ic6e59bb5c294273d0cff1daf66c73548806af66d
Signed-off-by: Bo Sun <bo.sun.cn@windriver.com>