kasan: test: fix redefinition of 'kmalloc_memmove_invalid_size' error
When enable the allyesconfig on yocto devshell, an error happens in test_kasan.c:

    kernel-source/lib/test_kasan.c:547:13: error: redefinition of 'kmalloc_memmove_invalid_size'
    |   547 | static void kmalloc_memmove_invalid_size(struct kunit *test)
    |       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 76645e0f5a2a ("kasan: test: add memcpy test that avoids out-of-bounds write")
Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>