serial: amba-pl011: remove undeclared callbacks in xlnx_sbsa_uart_pops
When we enable allsysconfig in devshell and compile the kernel on zynqmp bsp,
an error happens:

    amba-pl011.c:2251:27: error: 'pl011_release_port' undeclared here
    (not in a function); did you mean 'pl011_verify_port'?
    |  2251 |         .release_port   = pl011_release_port,
    |       |                           ^~~~~~~~~~~~~~~~~~
    |       |                           pl011_verify_port

    amba-pl011.c:2252:27: error: 'pl011_request_port' undeclared here
    (not in a function); did you mean 'pl011_verify_port'?
    |  2252 |         .request_port   = pl011_request_port,
    |       |                           ^~~~~~~~~~~~~~~~~~
    |       |                           pl011_verify_port

The pl011_release_port and pl011_request_port has been removed since
commit: d1180405c7b5 ("serial: amba-pl011: do not request memory region twice").
We need also update the xlnx_sbsa_uart_pops to line up with amba-pl011 generic
driver framework.

Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>