drm: bridge: it6161: add missing gpio consumer header
commit  4bf8c986c826113d4dd4ffa91e930dc288a8afc3 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Fix it6161.c:2810:24: error: implicit declaration of function
'devm_gpiod_get_optional'.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
Acked-by: Jason Liu <jason.hui.liu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>