LF 16506-1 net: ppfe: remove init_dummy_netdev
commit  fec2b2ee8f1b0cf6102942ae73a25afca82f9348 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

See:
commit f835bdae7167 ("net: remove init_dummy_netdev()")

drivers/staging/fsl_ppfe/pfe_hif.c:993:9: error: implicit declaration of function ‘init_dummy_netdev’ [-Werror=implicit-function-declaration]
  993 |         init_dummy_netdev(&hif->dummy_dev);
      |         ^~~~~~~~~~~~~~~~~

Reviewed-by: Wei Fang <wei.fang@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>