LF-16382 pxp_dma: uapi: Fix build break for pxp lib with GCC-15
commit  c08422adbebed91155def4af9fcf3a0e0894d951 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Fix the build break for imx-lib/pxp for the reason bool is now keyword.

linux/pxp_dma.h:27:23: error: 'bool' cannot be defined via 'typedef'
    27  typedef unsigned char bool;
                              ^~~~

Also add __cplusplus check for bool compatibility in C/C++ environments.

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Reviewed-by: Guoniu Zhou <guoniu.zhou@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>