dt-bindings: iio: adc: versal-sysmon: Remove deprecated header inclusion
commit 7cac0b5838d66c43cdf15168195e4c72f46cc8fb from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.18

The commit 658a0e39dc01 ("xilinx: Move all DT binding headers to dt
folder") moved xlnx-versal-regnode.h to an arch-specific location,
causing the binding example compilation to fail with:
error: dt-bindings/power/xlnx-versal-regnode.h: No such file or directory

Define PM_REGNODE_SYSMON_ROOT_0 locally in the example section and remove
the header inclusion.

Signed-off-by: Sai Krishna Potthuri <sai.krishna.potthuri@amd.com>
Message-ID: <20260304150100.2713460-4-sai.krishna.potthuri@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>