ptp: xilinx: Ensure the driver is only build on 64 bit archs
commit 3840ebf85e9a6e26cb6e9971d77faa8476de4e7e from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.12

Driver doesn't support 32 bit machines. PTP adjustment calculations will
have additional delays if we use 32 bit arithmetic. Ensure the driver
build in 64 bit arch by simplifying the bitwise operations instead of
adding dependency in the kconfig.

Fixes the warnings:
/include/linux/bits.h:37:38: note: in expansion of macro '__GENMASK'
   37 |         (GENMASK_INPUT_CHECK(h, l) + __GENMASK(h, l))
      |                                      ^~~~~~~~~
drivers/ptp/ptp_xilinx.c:62:41: note: in expansion of macro 'GENMASK'
   62 | #define XPTPTIMER_MAX_SEC_MASK          GENMASK(XPTPTIMER_MAX_SEC_SIZE - 1, 0)
      |                                         ^~~~~~~
drivers/ptp/ptp_xilinx.c:113:51: note: in expansion of macro 'XPTPTIMER_MAX_SEC_MASK'
  113 |         ts->tv_sec = (((u64)sech << 32) | secl) & XPTPTIMER_MAX_SEC_MASK;
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/bits.h:6:
drivers/ptp/ptp_xilinx.c: In function 'xlnx_ptp_adjtime':
./include/vdso/bits.h:7:40: error: left shift count >= width of type [-Werror=shift-count-overflow]
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                        ^~
drivers/ptp/ptp_xilinx.c:64:41: note: in expansion of macro 'BIT'
   64 | #define XPTPTIMER_TOD_OFFSET_NEG        BIT(47)
      |                                         ^~~
drivers/ptp/ptp_xilinx.c:254:24: note: in expansion of macro 'XPTPTIMER_TOD_OFFSET_NEG'
  254 |                 sign = XPTPTIMER_TOD_OFFSET_NEG;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/ptp/ptp_xilinx.c: In function 'xlnx_ptp_timer_isr':
./include/linux/bits.h:35:18: error: right shift count is negative [-Werror=shift-count-negative]
   35 |          (~UL(0) >> (BITS_PER_LONG - 1 - (h))))
      |                  ^~
./include/linux/bits.h:37:38: note: in expansion of macro '__GENMASK'
   37 |         (GENMASK_INPUT_CHECK(h, l) + __GENMASK(h, l))

Fixes: b86076cc1737 ("ptp: Add Xilinx PTP timer driver with EXTTS support")
Signed-off-by: Abin Joseph <abin.joseph@amd.com>
Message-ID: <20250123085932.219095-1-abin.joseph@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>