LF-13827-7 net: pfe: Replace strlcpy() with strscpy() for many drivers
commit  27fdc4b323157ce5ee090815f9852dfcc5017a55 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Cope with upstream change:
commit d26270061ae6 ("string: Remove strlcpy()")

e.g.
../drivers/i2c/busses/i2c-flexio.c: In function ‘imx_flexio_i2c_master_probe’:
../drivers/i2c/busses/i2c-flexio.c:683:9: error: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Werror=implicit-function-declaration]
  683 |         strlcpy(i2c_dev->adapter.name, dev_name(i2c_dev->dev),
      |         ^~~~~~~
      |         strncpy

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>