fix fpga build error
Remove the unused codes to fix the below error.
xilinx-zynq/kernel-source/drivers/fpga/of-fpga-region.c:
  In function 'of_fpga_region_probe':
xilinx-zynq/kernel-source/drivers/fpga/of-fpga-region.c:436:42: error:
  macro "fpga_region_register" requires 3 arguments, but only 1 given
  436 |         ret = fpga_region_register(region);
      |
                                  ^

Reference: https://git.yoctoproject.org/linux-yocto/commit/drivers/fpga/of-fpga-region.c?h=v5.10/standard/base&id=af02dec83a48cd8b32266bb4bea7a557be974d35

Signed-off-by: Jinfeng Wang <jinfeng.wang.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>