gpiolib: cdev: removing unused variables from gpiolib-cdev
polarity_change flag, struct line eflags, and hte enable
flags were combined into a single flag variable in the commit
97e76fdb990("gpiolib: cdev: consolidate edge detector configuration flags").
polarity_change used but not defined and creates the below build error,
removed the variables not more needed for edge_detector_update function.

drivers/gpio/gpiolib-cdev.c:1395:17: error: ‘polarity_change’ undeclared

Signed-off-by: Rajeshkumar Ramasamy <rajeshkumar.ramasamy@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>