LF-15527-1 net: fec_uio: change to use ethtool_mmsv_link_state_handle
commit  264d8dd06fee744ce29e86a14018a93d256d902a from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Cope with upstream change:
commit 9ff2aa4206ef ("net: ethtool: mm: extract stmmac verification logic into common library")

../drivers/net/ethernet/freescale/fec_uio.c: In function ‘stmmac_mac_link_down’:
../drivers/net/ethernet/freescale/fec_uio.c:271:17: error: implicit declaration of function ‘stmmac_fpe_link_state_handle’; did you mean ‘ethtool_mmsv_link_state_handle’? [-Werror=implicit-function-declaration]
  271 |                 stmmac_fpe_link_state_handle(priv, false);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 ethtool_mmsv_link_state_handle

Reviewed-by: Vanshika Shukla <vanshika.shukla@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>