arm64: dts: imx8qm-ss-dma: Add missing fsl-edma.h include
Commit 97fdde3189b6 ("arm64: dts: imx8qm-ss-dma: correct the dma
channels of lpuart") introduced the use of FSL_EDMA_RX flag but missed
adding the required header file, causing DTC compilation error:

  Error: arch/arm64/boot/dts/freescale/imx8qm-ss-dma.dtsi:179.22-23 syntax error
  FATAL ERROR: Unable to parse input tree

Add the missing include for dt-bindings/dma/fsl-edma.h to fix the build
error.

Fixes: 97fdde3189b6 ("arm64: dts: imx8qm-ss-dma: correct the dma channels of lpuart")
Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>