MGS-8473 [#imx-3422] remove nth_page from gpu driver in 6.17 kernel
commit  35015d7b9a94e6347a1951a77096e6c872b77020 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Remove nth_page from gpu driver in 6.17 kernel.

Cope with upstream API change:
commit c506f8ec0d22 ("mm: remove nth_page()")
https://lore.kernel.org/all/20250901150359.867252-38-david@redhat.com/T/#u

drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:2265:28: error: implicit declaration of function ‘nth_page’; did you mean ‘pte_page’? [-Werror=implicit-function-declaration]
 2265 |                 pages[i] = nth_page(page, i);
      |                            ^~~~~~~~
      |                            pte_page

Signed-off-by: Guangliu Ding <guangliu.ding@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>