ASoC: fsl_micfil: Update macros
Fix the building error:
sound/soc/fsl/fsl_micfil.c:190:25: error: 'MICFIL_VAD0_NCONFIG_NOREN_SHIFT' undeclared here (not in a function); did you mean 'MICFIL_VAD0_NCONFIG_NOREN'?
  190 |                         MICFIL_VAD0_NCONFIG_NOREN_SHIFT,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is caused by the commits[1][2][3], the macros are modified in these
commits, replace the old macros with the new macros.

[1]https://git.yoctoproject.org/linux-yocto/commit/sound/soc/fsl/fsl_micfil.h?h=v5.10/standard/nxp-sdk-5.10/nxp-soc&id=226fc91c860b11bf33a710c55f4ac0f3e8a88f48
[2]https://git.yoctoproject.org/linux-yocto/commit/sound/soc/fsl/fsl_micfil.h?h=v5.10/standard/nxp-sdk-5.10/nxp-soc&id=b2a72a772ef08142a24e3bae1aa7fcc2f4cfc29f
[3]https://git.yoctoproject.org/linux-yocto/commit/sound/soc/fsl/fsl_micfil.h?h=v5.10/standard/nxp-sdk-5.10/nxp-soc&id=442dadf32d1cb169a5af36c7f204514c76b34517

Signed-off-by: Jinfeng Wang <jinfeng.wang.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>