firmware: xilinx: Fix two enum-int-mismatch errors
The SDK commit cdf530a25695 ("firmware: xilinx: Add ZynqMP firmware
ioctl enums for RPU configuration.") introduced two enum-int-mismatch
errors:
  drivers/firmware/xilinx/zynqmp.c:1823:5: error: conflicting types for ‘zynqmp_pm_set_rpu_mode’ due to enum/integer mismatch; have ‘int(u32,  enum rpu
  _oper_mode)’ {aka ‘int(unsigned int,  enum rpu_oper_mode)’} [-Werror=enum-int-mismatch]
   1823 | int zynqmp_pm_set_rpu_mode(u32 node_id, enum rpu_oper_mode rpu_mode)
        |     ^~~~~~~~~~~~~~~~~~~~~~
  In file included from drivers/firmware/xilinx/zynqmp.c:27:
  include/linux/firmware/xlnx-zynqmp.h:745:5: note: previous declaration of ‘zynqmp_pm_set_rpu_mode’ with type ‘int(u32,  u32)’ {aka ‘int(unsigned int,
    unsigned int)’}
    745 | int zynqmp_pm_set_rpu_mode(u32 node_id, u32 arg1);
        |     ^~~~~~~~~~~~~~~~~~~~~~
  drivers/firmware/xilinx/zynqmp.c:1841:5: error: conflicting types for ‘zynqmp_pm_set_tcm_config’ due to enum/integer mismatch; have ‘int(u32,  enum r
  pu_tcm_comb)’ {aka ‘int(unsigned int,  enum rpu_tcm_comb)’} [-Werror=enum-int-mismatch]
   1841 | int zynqmp_pm_set_tcm_config(u32 node_id, enum rpu_tcm_comb tcm_mode)
        |     ^~~~~~~~~~~~~~~~~~~~~~~~
  include/linux/firmware/xlnx-zynqmp.h:746:5: note: previous declaration of ‘zynqmp_pm_set_tcm_config’ with type ‘int(u32,  u32)’ {aka ‘int(unsigned in
  t,  unsigned int)’}
    746 | int zynqmp_pm_set_tcm_config(u32 node_id, u32 arg1);
        |     ^~~~~~~~~~~~~~~~~~~~~~~~

Fix them by using corresponding enums.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>