MGS-8538 gpu: fix build break after linux kernel upgrade to 6.18
commit  1d136e558ebd98e4510d4aec474b6d0861124372 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

backend/gpu/mali_kbase_irq_linux.c:427:25: error: implicit
declaration of function ‘hrtimer_init’; did you mean ‘hrtimers_init’?
[-Wimplicit-function-declaration]
427 |     hrtimer_init(&kbasep_irq_test_data.timer, CLOCK_MONOTONIC,

Related to: MGS-8197 [#ccc] Switch to use hrtimer_setup()

Signed-off-by: Ryan Zhang <ryan.zhang@nxp.com>
Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>