mxc: gpu-viv: delete set but unused 'timer' variable in gckCOMMAND_Stall()
commit  b11decbac4f53ab05531c3121e0178f0b77c93b2 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

In a clang-16 build with W=1 C=1, this warning is treated as an error:

drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_command.c:3609:17: error:
variable 'timer' set but not used [-Werror,-Wunused-but-set-variable]
    gctUINT     timer  = 0;
                ^

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>