spi: cadence-qspi: Fix redefinition of 'cqspi' in cqspi_exec_mem_op()
The stable commit 8df235f768ce ("spi: cadence-quadspi: Implement refcount
to handle unbind during busy") and the SDK commit 1eb6f605cfd5 ("spi:
spi-cadence-quadspi: Add Rx periodic Tuning support") use different
approaches to obtain the struct cqspi_st pointer and assign it to the
local variable 'cqspi'. This results in the following redefinition build
error:
  drivers/spi/spi-cadence-quadspi.c: In function ‘cqspi_exec_mem_op’:
  drivers/spi/spi-cadence-quadspi.c:1791:26: error: redefinition of ‘cqspi’
   1791 |         struct cqspi_st *cqspi = spi_controller_get_devdata(mem->spi->controller);

To resolve this issue, only one method should be retained. The approach
from the stable commit is preferred.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>