fs/aufs: fix a build error in debug.c when running make allyesconfig
When building linux yocto with allyesconfig, a build error is found:

fs/aufs/debug.c: In function ‘do_pri_inode’:
fs/aufs/debug.c:137:54: error: ‘struct inode’ has no member named
‘i_ctime’; did you mean ‘i_atime’?
  137 |              hn, (long long)timespec64_to_ns(&inode->i_ctime) &
      0x0ffff,
      |                                                      ^~~~~~~
make[4]: *** [scripts/Makefile.build:243: fs/aufs/debug.o] Error 1
make[4]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors

The member i_ctime in struct inode is renamed to __i_ctime and use the
accessor function inode_get_ctime() to fetch the current ctime from the
inode in the commit 13bc24457850 ("rename i_ctime field to __i_ctime")
at 6.6-rc1.
Use this function inode_get_ctime() to fetch the current ctime to fix
the build error.

Signed-off-by: Bin Lan <bin.lan.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>