MGS-8197 gpu: drop fence_value_str callback
commit  28960874ebc1272c3fd9dd99acdc84e600818e78 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

drop deprecated using of fence_value_str callback
Cope with upstream API change:
commit 2ce07fea3cc8 ("dma-buf/dma-fence: remove unnecessary callbacks")

drivers/gpu/arm/midgard/mali_kbase_fence_ops.c:76:49: error: ‘const struct dma_fence_ops’ has no member named ‘fence_value_str’
   76 |                                                .fence_value_str = kbase_fence_fence_value_str,
      |                                                 ^~~~~~~~~~~~~~~
drivers/gpu/arm/midgard/mali_kbase_fence_ops.c:76:67: error: initialization of ‘bool (*)(struct dma_fence *)’ {aka ‘_Bool (*)(struct dma_fence *)’} from incompatible pointer type ‘void (*)(struct dma_fence *, char *, int)’ [-Werror=incompatible-pointer-types]
   76 |                                                .fence_value_str = kbase_fence_fence_value_str,

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>