LF-1197-2 gpu: drm: imx: ipuv3: remove drmP.h
commit  5c2bb9ea1fc8658e4c0df7cb249c5497a5937fc6 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

API changes:
4e98f871bcff ("drm: delete drmP.h + drm_os_linux.h")

drivers/gpu/drm/imx/ipuv3/ipuv3-kms.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>