MGS-8076 drm/imx: dpu95-bliteng: fix the using of MODULE_IMPORT_NS in 6.13 kernel
commit  556bfe331b6eef5097c3e837de7be561f9f2672f from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Fix the using of MODULE_IMPORT_NS in 6.13 kernel.

drivers/gpu/drm/imx/dpu95/dpu95-blit.c:689:18: error: expected ‘,’ or ‘;’ before ‘DMA_BUF’
  689 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
API usage changed since
commit ocdd30ebb1b9f ("module: Convert symbol namespace to string literal")

Signed-off-by: Guangliu Ding <guangliu.ding@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>