drm: xlnx: hdmi: Fix errors reported by allmodconfig
commit ae971121244fbb190ee3164e75be475708ea4054 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.12

Fix below compilation error reported by allmodconfig

ERROR: modpost: "__aeabi_uldivmod" [drivers/gpu/drm/xlnx/xlnx_hdmi.ko]
undefined!
make[2]: *** [scripts/Makefile.modpost:145: Module.symvers] Error 1
make[1]: *** [/linux-xlnx/Makefile:1873: modpost] Error 2
make: *** [Makefile:234: __sub-make] Error 2

Signed-off-by: Rajesh Gugulothu <rajesh.gugulothu@amd.com>
Message-ID: <1737695638-916957-1-git-send-email-rajesh.gugulothu@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>