arm64/sysreg: Add _EL1 into ID_AA64PFR0_MPAM
The following compilation error was introduced by the commit c5796e8b5
("KVM: arm64: Hide unsupported MPAM from the guest"), in which the
register name is not aligned with the automatic generation convention
as per DDI0487I.a.

Add _EL1 into ID_AA64PFR0_MPAM to follow the ID_AA64PFR0_EL1 automatic
generation convention and then fix the build error.

| /arch/arm64/kvm/sys_regs.c: In function 'read_id_reg':
| /arch/arm64/kvm/sys_regs.c:1114:44: error: 'ID_AA64PFR0_MPAM_SHIFT' undeclared (first use in this function); did you mean 'ID_AA64PFR0_EL1_MPAM_SHIFT'?
|  1114 |                 val &= ~ARM64_FEATURE_MASK(ID_AA64PFR0_MPAM);
|       |                                            ^~~~~~~~~~~~~~~~

Signed-off-by: Liyin Zhang <liyin.zhang.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>