drm: bridge: adv7511: Fix building error
Fix the following error:
drivers/gpu/drm/bridge/adv7511/adv7511_drv.c:1036:17: error: implicit declaration of function 'adv7533_detach_dsi'; did you mean 'adv7533_attach_dsi'? [-Werror=implicit-function-declaration]
|  1036 |                 adv7533_detach_dsi(adv);
|       |                 ^~~~~~~~~~~~~~~~~~
|       |                 adv7533_attach_dsi

Function adv7533_detach_dsi is removed by commit [1]. Add the
logic according to commit [2].

[1] https://git.yoctoproject.org/linux-yocto/commit/drivers/gpu/drm/bridge/adv7511/adv7533.c?h=v5.10/standard/nxp-sdk-5.10/nxp-soc&id=09a817549036bd416880079dfb1a1633216528a5
[2] https://git.yoctoproject.org/linux-yocto/commit/drivers/gpu/drm/bridge/adv7511/adv7511_drv.c?h=v6.6/standard/nxp-sdk-6.6/nxp-soc&id=cb8e31c317c0e9cf47ba9b60ef4a5e230f446485

Signed-off-by: Jinfeng Wang <jinfeng.wang.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>