staging: dpaa2-evb: Update rtmsg_ifinfo() parameters
The API for rtmsg_ifinfo() was modified by the stable commit 2f9f4d4f33c8
("rtnetlink: pass netlink message header and portid to
rtnl_configure_link()"). To resolve the resulting build error, the
dpaa2-evb driver must be updated to call this function in accordance
with the new API.
  drivers/staging/fsl-dpaa2/evb/evb.c: In function ‘evb_probe’:
  drivers/staging/fsl-dpaa2/evb/evb.c:1291:25: error: too few arguments to function ‘rtmsg_ifinfo’
   1291 |                         rtmsg_ifinfo(RTM_NEWLINK, port_netdev,
        |                         ^~~~~~~~~~~~

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>