soc: imx: fix build error of missing imx_src_is_m4_enabled
commit  e59210683f997ca39d54aa5884326eaaf1289c0b from
https://github.com/nxp-imx/linux-imx lf-6.18.y

drivers/clk/imx/clk-gate2.o: In function `clk_gate2_do_shared_clks':
/home/b29396/Work/linux/dash-linux-devel/build_v8/../drivers/clk/imx/clk-gate2.c:61: undefined reference to `imx_src_is_m4_enabled'
drivers/clk/imx/clk-pfd.o: In function `clk_pfd_do_shared_clks':
/home/b29396/Work/linux/dash-linux-devel/build_v8/../drivers/clk/imx/clk-pfd.c:55: undefined reference to `imx_src_is_m4_enabled'
/home/b29396/Work/linux/dash-linux-devel/build_v8/../drivers/clk/imx/clk-pfd.c:55: undefined reference to `imx_src_is_m4_enabled'
drivers/clk/imx/clk-pllv3.o: In function `clk_pllv3_do_shared_clks':
/home/b29396/Work/linux/dash-linux-devel/build_v8/../drivers/clk/imx/clk-pllv3.c:109: undefined reference to `imx_src_is_m4_enabled'
/home/b29396/Work/linux/dash-linux-devel/Makefile:1047: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 1
make[1]: Leaving directory '/home/b29396/Work/linux/dash-linux-devel/build_v8'
Makefile:179: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

squash a347a229d70fa soc: imx8m: fix missing prototype

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>