tty/serial: serial-tegra: remove unused variable
This unused variable is introduced during porting sdk patch,
remove it to avoid below build error:
drivers/tty/serial/serial-tegra.c:742:23: error:
unused variable 'ier' [-Werror=unused-variable]
  742 |         unsigned long ier;

Signed-off-by: Meng Li <Meng.Li@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>