Revert: "net: stmmac: enable wakeup capability only when Network Proxy Agent is ready"
This reverts commit 5391643bb6f17db8dbf916dc1c21773601236a77 from
https://github.com/intel/linux-intel-lts.git

drivers/net/ethernet/stmicro/stmmac/stmmac_netproxy.c
error: 'struct np_netdev' has no member named 'proxy_wakeup_enable'

Signed-off-by: Li Wang <li.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>