LF-8317 drm: imx_mhdp: fix build issue
commit  797c8888af5694aa9d7e9e3b5a30815107019818 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Fix build issue for L6.2.x kernel.
Error logs:
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:67:21: error: variable ‘cdns_mhdp_imx_encoder_helper_funcs’ has initializer but incomplete type
   67 | static const struct drm_encoder_helper_funcs cdns_mhdp_imx_encoder_helper_funcs = {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:68:3: error: ‘const struct drm_encoder_helper_funcs’ has no member named ‘enable’
   68 |  .enable     = cdns_mhdp_imx_encoder_enable,
      |   ^~~~~~
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:68:16: warning: excess elements in struct initializer
   68 |  .enable     = cdns_mhdp_imx_encoder_enable,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:68:16: note: (near initialization for ‘cdns_mhdp_imx_encoder_helper_funcs’)
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:69:3: error: ‘const struct drm_encoder_helper_funcs’ has no member named ‘disable’
   69 |  .disable    = cdns_mhdp_imx_encoder_disable,
      |   ^~~~~~~
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:69:16: warning: excess elements in struct initializer
   69 |  .disable    = cdns_mhdp_imx_encoder_disable,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:69:16: note: (near initialization for ‘cdns_mhdp_imx_encoder_helper_funcs’)
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:70:3: error: ‘const struct drm_encoder_helper_funcs’ has no member named ‘atomic_check’
   70 |  .atomic_check = cdns_mhdp_imx_encoder_atomic_check,
      |   ^~~~~~~~~~~~
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:70:18: warning: excess elements in struct initializer
   70 |  .atomic_check = cdns_mhdp_imx_encoder_atomic_check,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:70:18: note: (near initialization for ‘cdns_mhdp_imx_encoder_helper_funcs’)
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c: In function ‘cdns_mhdp_imx_bind’:
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:196:2: error: implicit declaration of function ‘drm_encoder_helper_add’; did you mean ‘drm_encoder_cleanup’? [-Werror=implicit-function-declaration]
  196 |  drm_encoder_helper_add(encoder, &cdns_mhdp_imx_encoder_helper_funcs);
      |  ^~~~~~~~~~~~~~~~~~~~~~
      |  drm_encoder_cleanup
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c: At top level:
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:67:46: error: storage size of ‘cdns_mhdp_imx_encoder_helper_funcs’ isn’t known
   67 | static const struct drm_encoder_helper_funcs cdns_mhdp_imx_encoder_helper_funcs = {

Signed-off-by: Sandor Yu <Sandor.yu@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>
[ Liu Ying: Fix conflict to rebase on next-20250228 ]
Signed-off-by: Liu Ying <victor.liu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>