net: octeontx-83: Fix the uninitialized error in pki_ecc_intr_handler()
A typo in the SDK commit 2e5d8037c7cc ("octeontx-83: domain based driver
for 83xx") cause the following build error:
  drivers/net/ethernet/cavium/octeontx-83xx/pki_main.c: In function ‘pki_ecc_intr_handler’:
  drivers/net/ethernet/cavium/octeontx-83xx/pki_main.c:38:23: error: ‘pki’ is used uninitialized [-Werror=uninitialized]
     38 |         struct pki_t *pki = (struct pki_t *)pki;
        |                       ^~~
  drivers/net/ethernet/cavium/octeontx-83xx/pki_main.c:38:23: note: ‘pki’ was declared here
     38 |         struct pki_t *pki = (struct pki_t *)pki;
        |                       ^~~

Fix this by initializing the 'pki' with the correct value.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>