media: platform: vxe-vxd: Remove the redundant function umin()
commit 3e0db4894a014e7 (minmax: add umin(a, b) and umax(a, b)) introduces
the definition umin() in include/linux/minmax.h, remove the redundant
function umin() in the file h264_secure_parser.c to fix the following warning:
| /include/linux/minmax.h:33:49: error: expected identifier or '(' before ')' token
|    33 |                 __cmp(unique_x, unique_y, op); })
|       |                                                 ^
| /include/linux/minmax.h:38:17: note: in expansion of macro '__cmp_once'
|    38 |                 __cmp_once(x, y, __UNIQUE_ID(__x), __UNIQUE_ID(__y), op))
|       |                 ^~~~~~~~~~
| /include/linux/minmax.h:61:9: note: in expansion of macro '__careful_cmp'
|    61 |         __careful_cmp((x) + 0u + 0ul + 0ull, (y) + 0u + 0ul + 0ull, <)
|       |         ^~~~~~~~~~~~~
| /drivers/media/platform/vxe-vxd/decoder/h264_secure_parser.c:174:28: note: in expansion of macro 'umin'
|   174 | static inline unsigned int umin(unsigned int a, unsigned int b)

Reference:
[https://git.yoctoproject.org/linux-yocto/commit/drivers/media/platform/vxe-vxd/decoder/h264_secure_parser.c?h=v5.15/standard/ti-sdk-5.10/ti-j72xx&id=76733de6d5610ffbe04b0a8836efa76f1778b114]

Signed-off-by: Jinfeng Wang <jinfeng.wang.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>