Revert "fsl-dcu: Revert "dma-mapping: remove dma_release_declared_memory""
This reverts commit 53a3f1aea2c8f099ef82e49d0153b068d9db23fe.

There is no one using dma_release_declared_memory(), and it also cause
following build error due to the API change introduced by stable commit
99326214f90c ("dma-mapping: Add dma_release_coherent_memory to DMA
API"):
  kernel/dma/coherent.c: In function ‘dma_release_declared_memory’:
  kernel/dma/coherent.c:140:37: error: passing argument 1 of ‘dma_release_coherent_memory’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    140 |         dma_release_coherent_memory(mem);
        |                                     ^~~
        |                                     |
        |                                     struct dma_coherent_mem *
  In file included from include/linux/dma-direct.h:10,
                   from kernel/dma/coherent.c:10:
  include/linux/dma-map-ops.h:170:49: note: expected ‘struct device *’ but argument is of type ‘struct dma_coherent_mem *’
    170 | void dma_release_coherent_memory(struct device *dev);
        |                                  ~~~~~~~~~~~~~~~^~~

So revert this commit to fix the build failure.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>