LF-15527-2 arch: imx: gpcv2: fix the build of irq_domain_add_hierarchy
commit  88bc4a90d1a95eeaffa4aabbeb992e51a5a3f485 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Caused by the commit
42b8b16fe56c ("irqdomain: Drop irq_domain_add_*() functions")

../arch/arm/mach-imx/gpcv2.c: In function ‘imx_gpcv2_init’:
../arch/arm/mach-imx/gpcv2.c:679:18: error: implicit declaration of function ‘irq_domain_add_hierarchy’; did you mean ‘irq_domain_is_hierarchy’? [-Werror=implicit-function-declaration]
  679 |         domain = irq_domain_add_hierarchy(parent_domain, 0, GPC_MAX_IRQS,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
      |                  irq_domain_is_hierarchy

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>