MGS-7214: gpu: imx: import DMA_BUF module namespace
commit  cea0476ec7dbfc8887821db09e794f00bc25b5f3 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Build breaks when compiled as module, as follows:

MODPOST Module.symvers
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_attach
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_map_attachment
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_unmap_attachment
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_get
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_put
  from namespace DMA_BUF, but does not import it.
ERROR: modpost: module imx-dpu-render uses symbol dma_buf_detach
 from namespace DMA_BUF, but does not import it.

Fixes: commit 5b8ce4a9037 ("MGS-7214: gpu: imx: dpu-blit: add generic dma-buf cache coherency management")
Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>
Reviewed-by: Xianzhong Li <xianzhong.li@nxp.com>
Reviewed-by: Guangliu Ding <guangliu.ding@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>