fs/yaffs2: fix a build warning in yaffs_tagsmarshall.c when running make allyesconfig
When building linux yocto with allyesconfig, a build warning is found:

fs/yaffs2/yaffs_tagsmarshall.c:188:6: error: no previous prototype for
‘yaffs_tags_marshall_install’ [-Werror=missing-prototypes]
  188 | void yaffs_tags_marshall_install(struct yaffs_dev *dev)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Inspect the code that the function yaffs_tags_marshall_install() is
declared in this header file yaffs_tagsmarshall.h. So include the
header file in yaffs_tagsmarshall.c.

Signed-off-by: Bin Lan <bin.lan.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>