coresight: tmc: etr: Handle enumeration value for CS_MODE_READ_PREVBOOT
commit 8c965214b660cfd78ad36535093c52e7f777a2ca from
git@git.assembla.com:cavium/WindRiver.linux.git

A new `CS_MODE_READ_PREVBOOT` mode was introduced by Commit 7476fa6c3dcd
("coresight: tmc: etr: Add support for Marvell OcteonTX2"). However, this
mode was not accounted for in the `switch` statement of `etm4_disable()`.

This leads to a build failure when `CONFIG_WERROR` is enabled, with the
following error message:

drivers/hwtracing/coresight/coresight-etm4x-core.c:1050:9: error:
enumeration value 'CS_MODE_READ_PREVBOOT' not handled in switch
[-Werror=switch]
 1050 |         switch (mode) {
      |         ^~~~~~

Suggested-by: Wladislav Wiebe <wladislav.wiebe@nokia.com>
Signed-off-by: Amit Singh Tomar <amitsinght@marvell.com>
Change-Id: Id9ff103937119b849c77b76e49eaeb5e03eb46a8
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/144052
Tested-by: sa_ip-sw-jenkins <sa_ip-sw-jenkins@marvell.com>
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Integrated-by: Jinchao Li <jinchao.li@windriver.com>