drm: xlnx: hdcp: Add missing slab.h include
commit 43c125aad48aa9dc4aa6403c15e302c7d2efe56e from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.18

This fixes the following build error:
drivers/gpu/drm/xlnx/hdcp/xlnx_hdcp2x_tx.c:614:18: error: implicit
declaration of function 'kzalloc'

Signed-off-by: Rajesh Gugulothu <rajesh.gugulothu@amd.com>
Message-ID: <20260224132312.800533-3-rajesh.gugulothu@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>