mxc: gpu-viv: remove set but unused 'timer' in gctaHARDWARE_SetMMU()
commit  17ed3fab14fae33c68a77b83f20b0b611bf4e869 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

drivers/mxc/gpu-viv/hal/security_v1/gc_hal_ta_hardware.c:499:15: error:
variable 'timer' set but not used [-Werror,-Wunused-but-set-variable]
    gctUINT32 timer = 0;
              ^
1 error generated.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>