LF-14100 video: fbdev: mxcfb_hx8369_wvga: Use backlight_is_blank()
commit  c15c4fa6102c62c9a014ce0e45e28c5b3b30cf3f from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Upstream commit 4551978bb50a ("backlight: Remove fb_blank from
struct backlight_properties") removes fb_blank from struct
backlight_properties, which causes build break for this driver:

drivers/video/fbdev/mxc/mxcfb_hx8369_wvga.c: In function ‘mipid_bl_update_status’:
drivers/video/fbdev/mxc/mxcfb_hx8369_wvga.c:397:22: error: ‘struct backlight_properties’ has no member named ‘fb_blank’
  397 |             bl->props.fb_blank != FB_BLANK_UNBLANK)
      |                      ^
drivers/video/fbdev/mxc/mxcfb_hx8369_wvga.c: In function ‘mipid_init_backlight’:
drivers/video/fbdev/mxc/mxcfb_hx8369_wvga.c:448:18: error: ‘struct backlight_properties’ has no member named ‘fb_blank’
  448 |         bl->props.fb_blank = FB_BLANK_UNBLANK;
      |                  ^

To fix this issue, stop reading/writing to this field and
use backlight_is_blank() to determine whether the backlight
is blank or not.  While at it, initialize bl->props.power to
BACKLIGHT_POWER_ON instead of FB_BLANK_UNBLANK, because kernel
documentation of power says the possible values of it are
constants BACKLIGHT_POWER_ON, BACKLIGHT_POWER_OFF and
BACKLIGHT_POWER_REDUCED(deprecated).

Signed-off-by: Liu Ying <victor.liu@nxp.com>
Reviewed-by: Sandor Yu <Sandor.yu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>