LF-1011-23 gpu: drm: bridge: dsim: update using of drm_panel_get_modes
commit  a206eb310cf9e24a640830847d7ebfc48d0d5cc1 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

API changed since:
0ce8ddd8e06d ("drm/panel: add drm_connector argument to get_modes()")

../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_connector_get_modes’:
../drivers/gpu/drm/bridge/sec-dsim.c:1798:9: error: too few arguments to function ‘drm_panel_get_modes’
 1798 |  return drm_panel_get_modes(dsim->panel);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>