net: tsn: Reduce arguments to genlmsg_multicast_allns()
Fix the following build errors:
net/tsn/genl_tsn.c:3651:15: error: too many arguments to function 'genlmsg_multicast_allns'
 3651 |         res = genlmsg_multicast_allns(&tsn_family, skb, 0,
      |               ^~~~~~~~~~~~~~~~~~~~~~~
This is caused by commit 4af714e82379984974a1b61a5629cdb302673dda, the @flags
parameter of function genlmsg_multicast_allns() is useless, then remove the
arguments when calling function genlmsg_multicast_allns().

Signed-off-by: Jinfeng Wang <jinfeng.wang.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>