OF: configfs: drop unused overlay_lock
No one is using this lock and drop it to fix the following error when
CONFIG_PREEMPT_RT and CONFIG_WERROR are both enabled:

    drivers/of/configfs.c:46:21: error: ‘overlay_lock’ defined but not used [-Werror=unused-variable]
    46 | static DEFINE_MUTEX(overlay_lock);
       |                     ^~~~~~~~~~~~
    include/linux/mutex.h:112:22: note: in definition of macro ‘DEFINE_MUTEX’
    112 |         struct mutex mutexname = __MUTEX_INITIALIZER(mutexname)
        |                      ^~~~~~~~~

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>