media: microchip: fix an unused-but-set warning
commit 490ea4d7bcc8e30606604d23b4d43f0f3a6378be from
https://github.com/linux4microchip/linux.git

Clang allmodconfig builds report:
../drivers/media/platform/microchip/microchip-vcpp.c:788:25: error: variable 'mchp_vcpp' set but not used [-Werror,-Wunused-but-set-variable]
        struct mchp_vcpp_fpga *mchp_vcpp;

Drop the variable, and cull the unneeded switch statement in the
process.

Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>