net: sdk_dpaa: fix build issue by using struct kernel_ethtool_ts_info
commit  0e93a2685d01fe2fbe755f5cc7c73b90c2097995 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

API changed since the commit
2111375b85ad ("net: Add struct kernel_ethtool_ts_info")

drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethtool.c:560:24: error: initialization of ‘int (*)(struct net_device *, struct kernel_ethtool_ts_info *)’ from incompatible pointer type ‘int (*)(struct net_device *, struct ethtool_ts_info *)’ [-Werror=incompatible-pointer-types]
  560 |         .get_ts_info = dpaa_get_ts_info,
      |                        ^~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>