net/fec_uio: drop deprecated priv->speed
commit  c03069981a0a68fcc659c7de53f6801202b346e0 from
https://github.com/nxp-imx/linux-imx lf-6.18.y

Cope with upstream change
commit 64fdb808660d ("net: stmmac: remove write-only priv->speed")

drivers/net/ethernet/freescale/fec_uio.c:355:13: error: ‘struct stmmac_priv’ has no member named ‘speed’
  355 |         priv->speed = speed;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Vanshika Shukla <vanshika.shukla@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>